name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - run: bun install

      - name: Build
        run: bun run build

      - name: Find build output
        id: find-output
        run: |
          if [ -d ".output/public" ]; then
            echo "path=.output/public" >> $GITHUB_OUTPUT
            echo "Found .output/public"
          elif [ -d "dist" ]; then
            echo "path=dist" >> $GITHUB_OUTPUT
            echo "Found dist"
          elif [ -d "build" ]; then
            echo "path=build" >> $GITHUB_OUTPUT
            echo "Found build"
          elif [ -d ".vinxi/output/public" ]; then
            echo "path=.vinxi/output/public" >> $GITHUB_OUTPUT
            echo "Found .vinxi/output/public"
          else
            echo "No build output found!"
            ls -la
            exit 1
          fi

      - name: Add .nojekyll
        run: touch ${{ steps.find-output.outputs.path }}/.nojekyll

      - name: List final output
        run: |
          echo "Final output directory: ${{ steps.find-output.outputs.path }}"
          ls -la ${{ steps.find-output.outputs.path }}

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.find-output.outputs.path }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4